version: "3.4"

services:
  node:
    image: connextproject/vector_node:0.2.5-beta.6
    ports:
      - 8002:8000
    environment:
      VECTOR_CONFIG: '{
        "adminToken": "cxt1234", 
        "authUrl":"http://auth:5040", 
        "natsUrl": "nats://nats:4222", 
        "messagingUrl": "", 
        "logLevel": "debug", 
        "chainAddresses": { 
          "1337": { 
            "channelMastercopyAddress": "0x8CdaF0CD259887258Bc13a92C0a6dA92698644C0", 
            "channelFactoryAddress": "0xF12b5dd4EAD5F743C6BaA640B0216200e89B60Da", 
            "hashlockTransferAddress": "0x345cA3e014Aaf5dcA488057592ee47305D9B3e10", 
            "withdrawAddress": "0xf25186B5081Ff5cE73482AD761DB0eB0d25abfBF", 
            "testTokenAddress": "0x9FBDa871d559710256a2502A2517b794B482Db40",
            "transferRegistryAddress": "0x8f0483125FCb9aaAEFA9209D8E9d7b9C8B9Fb90F" 
          }
        }, 
        "chainProviders": { 
          "1337": "http://blockchain:8545" 
        }, 
        "port": 3001, 
        "redisUrl": "redis://redis:6379", 
        "allowedSwaps": [ ], 
        "nodeUrl": "http://node:8000", 
        "rebalanceProfiles": [ 
          { 
            "chainId": 1337, 
            "assetId": "0x0000000000000000000000000000000000000000",
            "reclaimThreshold": "200000000000000000", 
            "target": "100000000000000000", 
            "collateralizeThreshold": "50000000000000000" 
          },{ 
            "chainId": 1337, 
            "assetId": "0x9FBDa871d559710256a2502A2517b794B482Db40", 
            "reclaimThreshold": "2000000000000000000", 
            "target": "1000000000000000000", 
            "collateralizeThreshold": "500000000000000000" 
          }
        ], 
        "awsAccessId": "", 
        "awsAccessKey": "", 
        "domainName": "", 
        "production": false         
      }'
      VECTOR_ENV: "dev"
      VECTOR_PROD: "true"
      VECTOR_MNEMONIC: "candy maple cake sugar pudding cream honey rich smooth crumble sweet treat"
      VECTOR_MNEMONIC_FILE: ""
      VECTOR_PG_DATABASE: "vector"
      VECTOR_PG_HOST: "database-node"
      VECTOR_PG_PASSWORD: "vector"
      VECTOR_PG_PASSWORD_FILE: ""
      VECTOR_PG_PORT: "5432"
      VECTOR_PG_USERNAME: "vector"
    depends_on:
      - database-node
      - blockchain
      - messaging

  router:
    image: connextproject/vector_router:0.2.5-beta.6
    ports:
      - 8008:8000
    environment:
      VECTOR_CONFIG: '{
        "adminToken": "cxt1234",
        "messagingUrl": "",
        "logLevel": "debug",
        "chainAddresses": { 
          "1337": { 
            "channelMastercopyAddress": "0x8CdaF0CD259887258Bc13a92C0a6dA92698644C0", 
            "channelFactoryAddress": "0xF12b5dd4EAD5F743C6BaA640B0216200e89B60Da", 
            "hashlockTransferAddress": "0x345cA3e014Aaf5dcA488057592ee47305D9B3e10", 
            "withdrawAddress": "0xf25186B5081Ff5cE73482AD761DB0eB0d25abfBF", 
            "testTokenAddress": "0x9FBDa871d559710256a2502A2517b794B482Db40",
            "transferRegistryAddress": "0x8f0483125FCb9aaAEFA9209D8E9d7b9C8B9Fb90F" 
          } 
        }, 
        "chainProviders": { 
          "1337": "http://blockchain:8545" 
        }, 
        "port": 3001, 
        "redisUrl": "redis://redis:6379", 
        "allowedSwaps": [ ], 
        "nodeUrl": "http://node:8000", 
        "rebalanceProfiles": [ 
          { 
            "chainId": 1337, 
            "assetId": "0x0000000000000000000000000000000000000000",
            "reclaimThreshold": "200000000000000000", 
            "target": "100000000000000000", 
            "collateralizeThreshold": "50000000000000000" 
          },{ 
            "chainId": 1337, 
            "assetId": "0x9FBDa871d559710256a2502A2517b794B482Db40", 
            "reclaimThreshold": "2000000000000000000", 
            "target": "1000000000000000000", 
            "collateralizeThreshold": "500000000000000000" 
          }
        ], 
        "awsAccessId": "", 
        "awsAccessKey": "", 
        "domainName": "", 
        "production": false        
      }' 
      VECTOR_ENV: "dev"
      VECTOR_PROD: "true"
      VECTOR_NODE_URL: "http://node:8000"
      VECTOR_MNEMONIC: "candy maple cake sugar pudding cream honey rich smooth crumble sweet treat"
      VECTOR_PG_DATABASE: "vector"
      VECTOR_PG_HOST: "database-router"
      VECTOR_PG_PASSWORD: "vector"
      VECTOR_PG_PASSWORD_FILE: ""
      VECTOR_PG_PORT: "5432"
      VECTOR_PG_USERNAME: "vector"
      VECTOR_PORT: "8008"
    depends_on:
      - node
      - database-router

  database-node:
    image: connextproject/vector_database:0.2.5-beta.6
    ports:
      - 5434:5432
    environment:
      AWS_ACCESS_KEY_ID: ""
      AWS_SECRET_ACCESS_KEY: ""
      POSTGRES_DB: "vector"
      POSTGRES_PASSWORD: "vector"
      POSTGRES_PASSWORD_FILE: ""
      POSTGRES_USER: "vector"
      VECTOR_ADMIN_TOKEN: "cxt1234"
      VECTOR_ENV: "dev"

  database-router:
    image: connextproject/vector_database:0.2.5-beta.6
    ports:
      - 5435:5432
    environment:
      AWS_ACCESS_KEY_ID: ""
      AWS_SECRET_ACCESS_KEY: ""
      POSTGRES_DB: "vector"
      POSTGRES_PASSWORD: "vector"
      POSTGRES_PASSWORD_FILE: ""
      POSTGRES_USER: "vector"
      VECTOR_ADMIN_TOKEN: "cxt1234"
      VECTOR_ENV: "dev"

  blockchain:
    image: connextproject/vector_ethprovider:0.2.5-beta.6
    ports:
      - 8545:8545
    environment:
      MNEMONIC: "candy maple cake sugar pudding cream honey rich smooth crumble sweet treat"
      CHAIN_ID: "1337"

  auth:
    image: connextproject/vector_auth:0.2.5-beta.6
    environment:
      VECTOR_JWT_SIGNER_PRIVATE_KEY: "-----BEGIN RSA PRIVATE KEY-----MIIEowIBAAKCAQEAqU/GXp8MqmugQyRk5FUFBvlJt1/h7L3Crzlzejz/OxriZdq/lBNQW9S1kzGc7qjXprZ1Kg3zP6irr6wmvP0WYBGltWs2cWUAmxh0PSxuKdT/OyL9w+rjKLh4yo3ex6DX3Ij0iP01Ej2POe5WrPDS8j6LT0s4HZ1FprL5h7RUQWV3cO4pF+1kl6HlBpNzEQzocW9ig4DNdSeUENARHWoCixE1gFYo9RXm7acqgqCk3ihdJRIbO4e/m1aZq2mvAFK+yHTIWBL0p5PF0Fe8zcWdNeEATYB+eRdNJ3jjS8447YrcbQcBQmhFjk8hbCnc3Rv3HvAapk8xDFhImdVF1ffDFwIDAQABAoIBAGZIs2ZmX5h0/JSTYAAw/KCB6W7Glg4XdY21/3VRdD+Ytj0iMaqbIGjZz/fkeRIVHnKwt4d4dgN3OoEeVyjFHMdc4eb/phxLEFqiI1bxiHvtGWP4d6XsON9Y0mBL5NJk8QNiGZjIn08tsWEmA2bm9gkyj6aPoo8BfBqA9Q5uepgmYIPT2NtEXvTbd2dedAEJDJspHKHqBfcuNBVoVhUixVSgehWGGP4GX+FvAEHbawDrwULkMvgblH+X8nBtzikp29LNpOZSRRbqF/Da0AkluFvuDUUIzitjZs5koSEAteaulkZO08BMxtovQjh/ZPtVZKZ27POCNOgRsbm/lVIXRMECgYEA2TQQ2Xy6eO5XfbiT4ZD1Z1xe9B6Ti7J2fC0ZNNSXs4DzdYVcHNIuZqfK6fGqmByvSnFut7n5Po0z2FdXc7xcKFJdBZdFP3GLXbN9vpRPIk9b6n+0df471uTYwVocmAGXez++y73j5XzHQQW4WmmC5SlKjQUWCGkuzISVjRDtlZ0CgYEAx43KPrJxSijjE2+VWYjNFVuv6KilnWoA8I2cZ7TtPi4h//r5vyOUst0egR3lJ7rBof74VttQPvqAk3GN697IrE/bSwefwG2lM1Ta0KB3jn6b/iT4ckmaOB+v6aDHq/GPW6l/sxD0RIEelRYZlsNLepRgKhcQckhjnWzQuGWSl0MCgYBYJQ0BdeCm2vKejp1U2OL+Qzo1j4MJGi+DTToBepTlv9sNQkWTXKh/+HAcaHp2qI1qhIYOAWbov5zemvNegH5Vzrb5Yd40VPvd1s2c3csPfW0ryQ+PItFd8BkWvl8EQQEcf04KmNE3fF/QP2YFKvR30z3x5LKAT08yqEuYp9oC8QKBgQCfc9XqGU3bEya3Lg8ptt0gtt2ty6xiRwSvMoiKeZCkgdpbH6EWMQktjvBD/a5Q+7KjjgfD54SMfj/lEPR1R9QTk8/HeTUWXsaFaMVbtQ0zSEm/Xq1DLTrUo8U9qmJCK0gA10SZwe9dGctlF36k8DJMpWjd2QYkO2GVthBld4wV3wKBgC7S4q0wmcrQIjyDIFmISQNdOAJhR0pJXG8mK2jECbEXxbKkAJnLj73DJ+1OVBlx4HXx54PiEkV3M3iTinf5tBSi8nA2D3s829F65XKFli1RC4rJv+2ygH8PnXX9rQKhK/v6/jeelKquH8zy894hLZe7feSsWV9GMgb5l9p+UzWB-----END RSA PRIVATE KEY-----"
      VECTOR_JWT_SIGNER_PUBLIC_KEY: "-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqU/GXp8MqmugQyRk5FUFBvlJt1/h7L3Crzlzejz/OxriZdq/lBNQW9S1kzGc7qjXprZ1Kg3zP6irr6wmvP0WYBGltWs2cWUAmxh0PSxuKdT/OyL9w+rjKLh4yo3ex6DX3Ij0iP01Ej2POe5WrPDS8j6LT0s4HZ1FprL5h7RUQWV3cO4pF+1kl6HlBpNzEQzocW9ig4DNdSeUENARHWoCixE1gFYo9RXm7acqgqCk3ihdJRIbO4e/m1aZq2mvAFK+yHTIWBL0p5PF0Fe8zcWdNeEATYB+eRdNJ3jjS8447YrcbQcBQmhFjk8hbCnc3Rv3HvAapk8xDFhImdVF1ffDFwIDAQAB-----END PUBLIC KEY-----"
      VECTOR_NATS_URL: "nats://nats:4222"
      VECTOR_ADMIN_TOKEN: "cxt1234"
      VECTOR_PORT: "5040"
      VECTOR_ENV: "prod"
      VECTOR_PROD: "true"
    ports:
      - 5040:5040
    depends_on:
      - nats

  nats:
    image: connextproject/vector_nats:0.2.5-beta.6
    deploy:
      mode: global
    ports:
      - 4222:4222
      - 4221:4221
    environment:
      JWT_SIGNER_PUBLIC_KEY: "-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqU/GXp8MqmugQyRk5FUFBvlJt1/h7L3Crzlzejz/OxriZdq/lBNQW9S1kzGc7qjXprZ1Kg3zP6irr6wmvP0WYBGltWs2cWUAmxh0PSxuKdT/OyL9w+rjKLh4yo3ex6DX3Ij0iP01Ej2POe5WrPDS8j6LT0s4HZ1FprL5h7RUQWV3cO4pF+1kl6HlBpNzEQzocW9ig4DNdSeUENARHWoCixE1gFYo9RXm7acqgqCk3ihdJRIbO4e/m1aZq2mvAFK+yHTIWBL0p5PF0Fe8zcWdNeEATYB+eRdNJ3jjS8447YrcbQcBQmhFjk8hbCnc3Rv3HvAapk8xDFhImdVF1ffDFwIDAQAB-----END PUBLIC KEY-----"

  messaging:
    image: connextproject/vector_messaging_proxy:0.2.5-beta.6
    ports:
      - 3001:80
    environment:
      VECTOR_DOMAINNAME: ""
      VECTOR_AUTH_URL: "auth:5040"
      VECTOR_NATS_HOST: "nats"
    depends_on:
      - nats
      - auth

  iframe:
    image: connextproject/vector_iframe_app:0.2.5-beta.6
    ports:
      - 5000:5000
    environment:
      VECTOR_CONFIG: '{
        "adminToken": "cxt1234",
        "messagingUrl": "",
        "logLevel": "debug",
        "chainAddresses": { 
          "1337": { 
            "channelMastercopyAddress": "0x8CdaF0CD259887258Bc13a92C0a6dA92698644C0", 
            "channelFactoryAddress": "0xF12b5dd4EAD5F743C6BaA640B0216200e89B60Da", 
            "hashlockTransferAddress": "0x345cA3e014Aaf5dcA488057592ee47305D9B3e10", 
            "withdrawAddress": "0xf25186B5081Ff5cE73482AD761DB0eB0d25abfBF", 
            "testTokenAddress": "0x9FBDa871d559710256a2502A2517b794B482Db40",
            "transferRegistryAddress": "0x8f0483125FCb9aaAEFA9209D8E9d7b9C8B9Fb90F" 
          } 
        }, 
        "chainProviders": { 
          "1337": "http://blockchain:8545" 
        }, 
        "port": 3001, 
        "redisUrl": "redis://redis:6379", 
        "allowedSwaps": [ ], 
        "nodeUrl": "http://node:8000", 
        "rebalanceProfiles": [ 
          { 
            "chainId": 1337, 
            "assetId": "0x0000000000000000000000000000000000000000",
            "reclaimThreshold": "200000000000000000", 
            "target": "100000000000000000", 
            "collateralizeThreshold": "50000000000000000" 
          },{ 
            "chainId": 1337, 
            "assetId": "0x9FBDa871d559710256a2502A2517b794B482Db40", 
            "reclaimThreshold": "2000000000000000000", 
            "target": "1000000000000000000", 
            "collateralizeThreshold": "500000000000000000" 
          }
        ], 
        "awsAccessId": "", 
        "awsAccessKey": "", 
        "domainName": "", 
        "production": false        
      }' 
  
  core-iframe:
    image: hypernetlabs/hypernet-protocol-core-iframe
    ports:
      - 8090:80

  merchant-iframe:
    image: hypernetlabs/hypernet-protocol-merchant-iframe
    ports:
      - 5005:80

  developer-ui:
    image: hypernetlabs/hypernet-protocol-developer-ui
    ports: 
      - 5015:80

  test-merchant:
    image: node:14
    ports:
      - 5010:5010
    volumes:
      - ../test-merchant-connector/dist/server-bundle:/app
      - ../test-merchant-connector/dist/connector-bundle:/app/connector
    command:
      node /app/index.js