const errorCodes = {
  AcceptPaymentError: "01",
  AjaxError: "02",
  BalancesUnavailableError: "03",
  BlockchainUnavailableError: "04",
  ERC20ContractError: "05",
  GatewayActivationError: "06",
  GatewayAuthorizationDeniedError: "07",
  GatewayConnectorError: "08",
  GatewayValidationError: "09",
  GovernanceSignerUnavailableError: "10",
  HypernetGovernorContractError: "11",
  InsufficientBalanceError: "12",
  InvalidParametersError: "13",
  InvalidPaymentError: "14",
  InvalidPaymentIdError: "15",
  LogicalError: "16",
  MessagingError: "17",
  NonFungibleRegistryContractError: "18",
  OfferMismatchError: "19",
  PaymentCreationError: "20",
  PaymentFinalizeError: "21",
  PaymentStakeError: "22",
  PersistenceError: "23",
};

export default errorCodes;
