version: '3.4'

services:
  node:
    image: connextproject/vector_node:latest
    ports:
      - 8002:8000
    environment:
      VECTOR_CONFIG: '{ "adminToken": "cxt1234", "messagingUrl": "https://messaging.connext.network", "logLevel": "info", "chainAddresses": { "1337": { "channelMastercopyAddress": "0x8CdaF0CD259887258Bc13a92C0a6dA92698644C0", "channelFactoryAddress": "0xF12b5dd4EAD5F743C6BaA640B0216200e89B60Da", "hashlockTransferAddress": "0x345cA3e014Aaf5dcA488057592ee47305D9B3e10", "withdrawAddress": "0xf25186B5081Ff5cE73482AD761DB0eB0d25abfBF", "testTokenAddress": "0x8f0483125FCb9aaAEFA9209D8E9d7b9C8B9Fb90F", "transferRegistryAddress": "0x9FBDa871d559710256a2502A2517b794B482Db40" } }, "chainProviders": { "1337": "http://blockchain:8545" }, "port": 3001, "redisUrl": "redis://redis:6379", "allowedSwaps": [ ], "nodeUrl": "http://node:8000", "rebalanceProfiles": [ { "chainId": 1337, "assetId": "0x0000000000000000000000000000000000000000", "reclaimThreshold": "200000000000000000", "target": "100000000000000000", "collateralizeThreshold": "50000000000000000" }, { "chainId": 1337, "assetId": "0x8f0483125FCb9aaAEFA9209D8E9d7b9C8B9Fb90F", "reclaimThreshold": "2000000000000000000", "target": "1000000000000000000", "collateralizeThreshold": "500000000000000000" } ], "awsAccessId": "", "awsAccessKey": "", "domainName": "", "production": true }'
      VECTOR_ENV: 'dev'
      VECTOR_PROD: "true"
      VECTOR_MNEMONIC: 'candy maple cake sugar pudding cream honey rich smooth crumble sweet treat'
      VECTOR_MNEMONIC_FILE: ''
      VECTOR_PG_DATABASE: 'vector'
      VECTOR_PG_HOST: 'database'
      VECTOR_PG_PASSWORD: 'vector'
      VECTOR_PG_PASSWORD_FILE: ''
      VECTOR_PG_PORT: '5432'
      VECTOR_PG_USERNAME: 'vector'
    depends_on:
        - database
        - blockchain

  router:
    image: connextproject/vector_router
    ports:
      - 8008:8008
    environment:
      VECTOR_CONFIG: '{ "adminToken": "cxt1234", "messagingUrl": "https://messaging.connext.network", "logLevel": "info", "chainAddresses": { "1337": { "channelMastercopyAddress": "0x8CdaF0CD259887258Bc13a92C0a6dA92698644C0", "channelFactoryAddress": "0xF12b5dd4EAD5F743C6BaA640B0216200e89B60Da", "hashlockTransferAddress": "0x345cA3e014Aaf5dcA488057592ee47305D9B3e10", "withdrawAddress": "0xf25186B5081Ff5cE73482AD761DB0eB0d25abfBF", "testTokenAddress": "0x8f0483125FCb9aaAEFA9209D8E9d7b9C8B9Fb90F", "transferRegistryAddress": "0x9FBDa871d559710256a2502A2517b794B482Db40" } }, "chainProviders": { "1337": "http://blockchain:8545" }, "port": 3001, "redisUrl": "redis://redis:6379", "allowedSwaps": [ ], "nodeUrl": "http://node:8000", "rebalanceProfiles": [ { "chainId": 1337, "assetId": "0x0000000000000000000000000000000000000000", "reclaimThreshold": "200000000000000000", "target": "100000000000000000", "collateralizeThreshold": "50000000000000000" }, { "chainId": 1337, "assetId": "0x8f0483125FCb9aaAEFA9209D8E9d7b9C8B9Fb90F", "reclaimThreshold": "2000000000000000000", "target": "1000000000000000000", "collateralizeThreshold": "500000000000000000" } ], "awsAccessId": "", "awsAccessKey": "", "domainName": "", "production": true }'
      VECTOR_ENV: 'dev'
      VECTOR_PROD: "true"
      VECTOR_NODE_URL: 'http://node:8000'
      VECTOR_PG_DATABASE: 'vector'
      VECTOR_PG_HOST: 'database'
      VECTOR_PG_PASSWORD: 'vector'
      VECTOR_PG_PASSWORD_FILE: ''
      VECTOR_PG_PORT: '5432'
      VECTOR_PG_USERNAME: 'vector'
      VECTOR_PORT: '8008'
    depends_on:
        - node
        - database
        - blockchain

  database:
    image: connextproject/vector_database:latest
    ports:
      - 5434:5432
    environment:
      AWS_ACCESS_KEY_ID: ''
      AWS_SECRET_ACCESS_KEY: ''
      POSTGRES_DB: 'vector'
      POSTGRES_PASSWORD: 'vector'
      POSTGRES_PASSWORD_FILE: ''
      POSTGRES_USER: 'vector'
      VECTOR_ADMIN_TOKEN: 'cxt1234'
      VECTOR_ENV: 'dev'

  blockchain:
    image: connextproject/vector_ethprovider:latest
    ports: 
        - 8545:8545
    environment:
        MNEMONIC: 'candy maple cake sugar pudding cream honey rich smooth crumble sweet treat'
        CHAIN_ID: '1337'
