version: '3.4'

services:
  node:
    image: connextproject/vector_node:latest
    ports:
      - 8002:8000
    environment:
      VECTOR_CONFIG: '{ "adminToken": "cxt1234", "messagingUrl": "https://messaging.connext.network", "logLevel": "info", "chainAddresses": { "1337": { "channelMastercopyAddress": "0x83e4293c7c5782630A57DD60eEbE36BF20EfDfcD", "channelFactoryAddress": "0x084aeA04D0B333506e212B1e531cA223650bF284", "hashlockTransferAddress": "0xC2B65DC9BaAD68b0f01530009a4AF6CA438b8846", "withdrawAddress": "0xC0FA4A4cE403B5bcECD243121dC5874D9A65e5Bd", "testTokenAddress": "0xae3C262638994e968D6dfC8e58978b4301E7D51A", "transferRegistryAddress": "0xa227b9C3e0cE1f74029063a5b567D97BDed316e1" } }, "chainProviders": { "1337": "http://blockchain:8545" }, "port": 3001, "redisUrl": "redis://redis:6379", "allowedSwaps": [ ], "nodeUrl": "http://node:8000", "rebalanceProfiles": [ { "chainId": 1337, "assetId": "0x0000000000000000000000000000000000000000", "reclaimThreshold": "200000000000000000", "target": "100000000000000000", "collateralizeThreshold": "50000000000000000" }, { "chainId": 1337, "assetId": "0x8f0483125FCb9aaAEFA9209D8E9d7b9C8B9Fb90F", "reclaimThreshold": "2000000000000000000", "target": "1000000000000000000", "collateralizeThreshold": "500000000000000000" } ], "awsAccessId": "", "awsAccessKey": "", "domainName": "", "production": true }'
      VECTOR_ENV: 'dev'
      VECTOR_PROD: "true"
      VECTOR_MNEMONIC: "isolate income chaos sustain harsh suggest dawn kid sentence sad unable palace upper source below"
      VECTOR_MNEMONIC_FILE: ''
      VECTOR_PG_DATABASE: 'vector'
      VECTOR_PG_HOST: 'database'
      VECTOR_PG_PASSWORD: 'vector'
      VECTOR_PG_PASSWORD_FILE: ''
      VECTOR_PG_PORT: '5432'
      VECTOR_PG_USERNAME: 'vector'
    depends_on:
        - database
        - blockchain

  router:
    image: connextproject/vector_router
    ports:
      - 8008:8000
    environment:
      VECTOR_CONFIG: '{ "adminToken": "cxt1234", "messagingUrl": "https://messaging.connext.network", "logLevel": "info", "chainAddresses": { "1337": { "channelMastercopyAddress": "0x83e4293c7c5782630A57DD60eEbE36BF20EfDfcD", "channelFactoryAddress": "0x084aeA04D0B333506e212B1e531cA223650bF284", "hashlockTransferAddress": "0xC2B65DC9BaAD68b0f01530009a4AF6CA438b8846", "withdrawAddress": "0xC0FA4A4cE403B5bcECD243121dC5874D9A65e5Bd", "testTokenAddress": "0xae3C262638994e968D6dfC8e58978b4301E7D51A", "transferRegistryAddress": "0xa227b9C3e0cE1f74029063a5b567D97BDed316e1" } }, "chainProviders": { "1337": "http://blockchain:8545" }, "port": 3001, "redisUrl": "redis://redis:6379", "allowedSwaps": [ ], "nodeUrl": "http://node:8000", "rebalanceProfiles": [ { "chainId": 1337, "assetId": "0x0000000000000000000000000000000000000000", "reclaimThreshold": "200000000000000000", "target": "100000000000000000", "collateralizeThreshold": "50000000000000000" }, { "chainId": 1337, "assetId": "0x8f0483125FCb9aaAEFA9209D8E9d7b9C8B9Fb90F", "reclaimThreshold": "2000000000000000000", "target": "1000000000000000000", "collateralizeThreshold": "500000000000000000" } ], "awsAccessId": "", "awsAccessKey": "", "domainName": "", "production": true }'
      VECTOR_ENV: 'dev'
      VECTOR_PROD: "true"
      VECTOR_NODE_URL: 'http://node:8000'
      VECTOR_PG_DATABASE: 'vector'
      VECTOR_PG_HOST: 'database'
      VECTOR_PG_PASSWORD: 'vector'
      VECTOR_PG_PASSWORD_FILE: ''
      VECTOR_PG_PORT: '5432'
      VECTOR_PG_USERNAME: 'vector'
      VECTOR_PORT: '8008'
    depends_on:
        - node
        - database
        - blockchain

  database:
    image: connextproject/vector_database:latest
    ports:
      - 5434:5432
    environment:
      AWS_ACCESS_KEY_ID: ''
      AWS_SECRET_ACCESS_KEY: ''
      POSTGRES_DB: 'vector'
      POSTGRES_PASSWORD: 'vector'
      POSTGRES_PASSWORD_FILE: ''
      POSTGRES_USER: 'vector'
      VECTOR_ADMIN_TOKEN: 'cxt1234'
      VECTOR_ENV: 'dev'

  blockchain:
    image: connextproject/vector_ethprovider:latest
    ports: 
        - 8545:8545
    environment:
        MNEMONIC: "isolate income chaos sustain harsh suggest dawn kid sentence sad unable palace upper source below"
        CHAIN_ID: '1337'
