export enum ELinkStatus {
  INTENDED = 0, // [MESSAGING_ESTABLISHED]
  LINK_REQUEST_SENT = 1, // [LINK_REQUEST_SENT]
  MESSAGING_ESTABLISHED = 2, // [CHANNEL_OPENED]
  CHANNEL_OPENED = 3, // [STAKED]
  STAKED = 4, // [RUNNING, CLOSED]
  RUNNING = 5, // [DISPUTED, CLOSING]
  DISPUTED = 6, // [CLOSED]
  CLOSING = 7, // [CLOSED]
  CLOSED = 8,
  DENIED = 9,
}
