export enum ELinkStatus {
  INTENDED = 0, // [MESSAGING_ESTABLISHED]
  MESSAGING_ESTABLISHED = 1, // [CHANNEL_OPENED]
  CHANNEL_OPENED = 2, // [STAKED]
  STAKED = 3, // [RUNNING, CLOSED]
  RUNNING = 4, // [DISPUTED, CLOSING]
  DISPUTED = 5, // [CLOSED]
  CLOSING = 6, // [CLOSED]
  CLOSED = 7,
}
