export const PUBLIC_IDENTIFIER_DATA_BIND = '[data-bind="text: publicIdentifier"]';
export const MERCHANT_URL_INPUT_DATA_BIND = '[data-bind="textInput: merchantUrl"]';
export const TOKEN_SELECTOR_ID = "div#actionTokeSelector > div > #paymentToken";
export const DEPOSIT_BUTTON_ID = "#depositFunds";
export const ETHER_ASSET_TOTAL_AMOUNT_ID = "#assetAmount-0x0000000000000000000000000000000000000000";
export const HYPER_TOKEN_ASSET_TOTAL_AMOUNT_ID = "#assetAmount-0x9FBDa871d559710256a2502A2517b794B482Db40";
export const AUTHORIZE_MERCHANT_BUTTON_ID = "#authorizeMerchantButton";
export const PAYMENT_TYPE_SELECTOR_ID = "#paymentType";
export const COUNTER_PARTY_ADDRESS_INPUT_DATA_BIND = '[data-bind="textInput: remoteAccount"]';
export const REQUIED_STAKE_INPUT_DATA_BIND = '[data-bind="textInput: requiredStake"]';
export const PAYMENT_TOKEN_SELECTOR_ID = "div#paymentTokenSelector > div > #paymentToken";
export const PAYMENT_AMOUNT_INPUT_DATA_BIND = '[data-bind="textInput: amount"]';
export const AUTHORIZED_MERCHANT_SELECTOR_ID = "#authorizedMerchant";
export const SUBMIT_PAYMENT_BUTTON = "#submitPaymentButton";
