version: 2.1
jobs:
  build:
    docker:
      - image: "cimg/node:12.14.1"
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "this is the build job"
  test:
    docker:
      - image: "cimg/node:12.14.1"
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
    steps:
      - checkout
      - run: cd packages/hypernet-core && npm install
      - run: cd packages/hypernet-core && npm run test

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test
