version: 2.1
jobs:
  test:
    docker:
      - image: "cimg/node:12.14.1"
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
    pre:
      - echo "registry=https://registry.npmjs.org/" > ~/.npmrc
      - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
    steps:
      - checkout
      - run: yarn install
      - run: yarn test

# Orchestrate our job run sequence
workflows:
  test:
    jobs:
      - test
