export declare type Address = string;
export declare type Byte = string;
export declare type Bytes32 = string;
export declare type Bytes = string;
export declare type Uint8 = number;
export declare type Uint16 = number;
export declare type Uint24 = number;
export declare type Uint32 = number;
export declare type Uint40 = number;
export declare type Uint48 = number;
export declare type Uint56 = number;
export declare type Uint64 = string;
export declare type Uint128 = string;
export declare type Uint256 = string;
//# sourceMappingURL=types.d.ts.map