export declare const CHANNEL_FINALIZED = "Channel finalized.";
export declare const CHANNEL_NOT_FINALIZED = "Channel not finalized.";
export declare const CHANNEL_NOT_OPEN = "Channel not open.";
export declare const INVALID_SIGNATURES = "Invalid signatures";
export declare const NO_ONGOING_CHALLENGE = "No ongoing challenge.";
export declare const TURN_NUM_RECORD_DECREASED = "turnNumRecord decreased.";
export declare const TURN_NUM_RECORD_NOT_INCREASED = "turnNumRecord not increased.";
export declare const UNACCEPTABLE_WHO_SIGNED_WHAT = "Unacceptable whoSignedWhat array";
export declare const WHO_SIGNED_WHAT_WRONG_LENGTH = "_validSignatures: whoSignedWhat must be the same length as participants";
export declare const WRONG_CHANNEL_STORAGE = "Channel storage does not match stored version.";
export declare const CHALLENGER_NON_PARTICIPANT = "Challenger is not a participant";
export declare const RESPONSE_UNAUTHORIZED = "Response not signed by authorized mover";
export declare const WRONG_REFUTATION_SIGNATURE = "Refutation state not signed by challenger";
//# sourceMappingURL=revert-reasons.d.ts.map