site_name: Connext Documentation

repo_name: connext/vector
repo_url: https://github.com/connext/vector

theme:
  name: material

  logo: assets/logo.png
  favicon: assets/favicon.png

  font:
    text: Proxima Nova
  palette:
    primary: white

  features:
    - navigation.tabs

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/connext
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ConnextNetwork
    - icon: fontawesome/brands/medium
      link: https://medium.com/connext
    - icon: fontawesome/brands/discord
      link: https://discord.gg/FTxQc8C

nav:
  - Intro:
      - index.md
      - status.md
      - faq.md
  - Getting Started: gettingStarted.md
  - Node Guides:
      - deployProdNode.md
      - configureNode.md
      - integrateBrowserNode
  - Router Guides:
      - deployProdRouter.md
      - configureRouter.md
  - Reference:
      - nodeAPI.md
